name: Build and Push Docker Image to Harbor

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 소스 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # QEMU 설정 (다중 아키텍처 빌드를 위한 준비)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # Docker Buildx 설정
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Harbor 레지스트리에 로그인
      - name: Login to Harbor Registry
        uses: docker/login-action@v2
        with:
          registry: harbor.20.214.117.134.nip.io
          username: 'admin'
          password: 'Harbor12345'

      # Docker 이미지 빌드 및 푸시
      - name: Build and Push Docker Image
        env:
          # (옵션) 필요하다면 insecure registry 관련 환경 변수 설정 (빌드 시 참고)
          BUILDKIT_INSECURE_REGISTRY: harbor.20.214.117.134.nip.io
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: harbor.20.214.117.134.nip.io/frontend/msa-front:latest
